version: 2
jobs:
  php:
    working_directory: ~/signer
    docker:
    - image: circleci/php:7
    steps:
    - checkout:
        path: ~/signer
    - run: composer install
    - run: php ./php/tests/signer_test.php
  node:
    working_directory: ~/signer/node
    docker:
    - image: circleci/node:8
    steps:
    - checkout:
        path: ~/signer
    - run: npm install
    - run: ./node_modules/.bin/mocha
  node-hebe:
    working_directory: ~/signer-hebe/hebe-node
    docker:
      - image: circleci/node:12
    steps:
      - checkout:
          path: ~/signer-hebe
      - run: npm install
      - run: ./node_modules/.bin/mocha
  jvm:
    working_directory: ~/signer
    docker:
    - image: circleci/openjdk:8
    steps:
    - checkout:
        path: ~/signer
    - run: ./gradlew :jvm:check jacocoTestReport
    - store_test_results:
        path: ./build/test-results
  jvm-hebe:
    working_directory: ~/signer
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout:
          path: ~/signer
      - run: ./gradlew :hebe-jvm:check jacocoTestReport
      - store_test_results:
          path: ./build/test-results
  python:
    working_directory: ~/signer/python
    docker:
    - image: circleci/python:3.6
    steps:
    - checkout:
        path: ~/signer
    - run: pip install --user .[testing]
    - run: python -m pytest .
  python-hebe:
    working_directory: ~/signer/hebe-python
    docker:
    - image: circleci/python:3.8
    steps:
    - checkout:
        path: ~/signer
    - run: pip install --user .[testing]
    - run: python -m pytest .

  dotnet:
    working_directory: ~/signer/dotnet
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout:
          path: ~/signer
      - run: dotnet restore
      - run: dotnet test
  dotnet-hebe:
    working_directory: ~/signer/hebe-dotnet
      docker:
        - image: mcr.microsoft.com/dotnet/core/sdk:3.1
      steps:
        - checkout:
            path: ~/signer/hebe-dotnet
        - run: dotnet restore
        - run: dotnet test
  dart-hebe:
    working_directory: ~/signer/hebe-dart
    docker:
    - image: google/dart
    steps:
    - checkout:
            path: ~/signer
    - run: pub get
    - run: pub run test

workflows:
  version: 2
  test:
    jobs:
    - php
    - node
    - node-hebe
    - jvm
    - jvm-hebe
    - python
    - python-hebe
    - dotnet
    - dart-hebe
